#!/bin/bash

#inicializo variables a utilizar en el cronometro
inicio=0
final=0
ejecutado=0
tiempoAcumulado=0

#mismo do while de siempre
while true; do
	#muestro menu de opciones y guardo seleccion del usuario
	echo "Selecciona una de las siguientes opciones: "
	echo "1 - Iniciar cronometro"
	echo "2 - Detener cronometro"
	echo "3 - Reiniciar cronometro"
	echo "4 - Salir del programa"
	read opcion

	#evaluo opcion con un case
	case $opcion in
	1)
	if [ $ejecutado == 0 ]; then
		#captura tiempo actual en segundos
		inicio=$(date +%s)
		#marca que el cronometro se esta ejecutando
		ejecutado=1
		echo "Cronometro iniciado"
	else
		echo "El cronometro esta ejecutado"
	fi
	;;
	2)
	if [ $ejecutado == 1 ]; then
		#marca que el cronometro ya no se esta ejecutando
		ejecutado=0
		#captura tiempo actual en segundos
		final=$(date +%s)
		#calcula el tiempo transcurrido
		tiempo=$(($final - $inicio))
		#suma al tiempo acumulado
		tiempoAcumulado=$(($final - $inicio + $tiempoAcumulado))
		echo "El tiempo fue de $tiempo."
		echo "El tiempo total es de $tiempoAcumulado."
	else
		echo "El cronometro no esta ejecutado"
	fi
	;;
	3)
		#reinicia el cromometro asignando los valores 0 como al inicio
		inicio=0
		final=0
		ejecutado=0
		tiempoAcumulado=0
		echo "Cronometro reiniciado"
	;;
	4)
		echo "Saliendo del programa..."
		exit 1
	;;
	*)	
		echo "Error, tiene que seleccionar una opcion de las siguientes: 1, 2, 3 o 4."
	;;
	esac
done
