#!/bin/bash

#configuro la clave de la api
api_key="d41215f0d47e4d738f204312242206"

#pido y asigno variable ciudad
read -p "Ingrese nombre de ciudad: " ciudad

#adapta la variable para que pueda ser correctamente procesada por la api
ciudad_encode=$(echo $ciudad | sed 's/ /%20/g')

#forma la url de la api
URL="http://api.weatherapi.com/v1/current.json?key=$api_key&q=$ciudad_encode&lang=es" 

#realiza la solicitud a la api y guarda la respuesta en una variable temporal
response=$(curl -s $URL)

#verifica si hubo un error en la solicitud y si hubo lo muestra
if echo $response | jq -e .error >/dev/null; then
    echo "Error: $(echo $response | jq -r .error.message)"
    exit 1
fi

#extrae la informacion relevante del json usando jq
temperatura=$(echo "$response" | jq -r '.current.temp_c')
descripcion=$(echo "$response" | jq -r '.current.condition.text')

#muestra la informacion
echo "El clima actual en $ciudad es: $descripcion"
echo "La temperatura actual es: $temperatura °C"
